# Simple configuration for an HTTP proxy listening on port 80 on all
# interfaces and forwarding requests to a single backend "servers" with a
# single server "server1" listening on 127.0.0.1:8000
global
  daemon
  maxconn 256

defaults
  mode http
  timeout connect 5000ms
  timeout client 50000ms
  timeout server 50000ms

frontend http-in
  bind *:8000
  default_backend servers

backend servers
  server SB-LAX 127.0.0.1:9080 maxconn 32
  server SB-NYC 127.0.0.1:9090 maxconn 32
  server SB-SEA 127.0.0.1:10080 maxconn 32

