apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  generation: 1
  namespace: $$NAMESPACE
  labels:
        environment: $$DEPLOYMENT_ENVIRONMENT
        app: vap-saas-sb
        tenancy : multiple-tenants
        removekey: $$REMOVE_KEY
  name: vap-saas-sb
spec:
  replicas: $$NO_OF_REPLICAS
  serviceName: vap-saas-sb-svc-$$VRBC_BUILD_NUMBER
  selector:
    matchLabels:
        environment: $$DEPLOYMENT_ENVIRONMENT
        app: vap-saas-sb
        tenancy : multiple-tenants
  template:
    metadata:
      annotations:
              scheduler.alpha.kubernetes.io/affinity: >
                {
                  "podAntiAffinity": {
                    "requiredDuringSchedulingIgnoredDuringExecution": [
                      {
                        "labelSelector": {
                          "matchExpressions": [
                            {
                              "key": "app",
                              "operator": "In",
                              "values": ["vap-saas-sb"]
                            }
                          ]
                        },
                        "namespaces": ["$$NAMESPACE"],
                        "topologyKey": "kubernetes.io/hostname"
                      }
                    ]
                  }
                }
      labels:
        environment: $$DEPLOYMENT_ENVIRONMENT
        app: vap-saas-sb
        tenancy : multiple-tenants
        removekey: $$REMOVE_KEY
    spec:
      containers:
      - image: $$IMAGE_REPOSITORY/vap-saas/vap-saas-sb:$$VRBC_BUILD_NUMBER
        imagePullPolicy: IfNotPresent
        name: vap-saas-sb
        ports:
        - containerPort: 9080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        env:
        - name: LEMANS_RESOURCES_URL
          value: $$LEMANS_RESOURCES_URL
        volumeMounts:
        - mountPath: /var/log
          name: li-logs
        - mountPath: /opt/vmware/vap-saas/config/csp
          name: csp-secret
        - mountPath: /opt/vmware/vap-saas/config/app
          name: app-secret
        imagePullPolicy: IfNotPresent
        resources:
         requests:
            cpu: "$$APP_CPU_REQUESTS"
            memory: "$$APP_MEM_REQUESTS"
         limits:
            cpu: "$$APP_CPU_LIMITS"
            memory: "$$APP_MEM_LIMITS"
        livenessProbe:
          httpGet:
            path: /vap-saas/api/vaphealth/health-alive
            port: 9080
          initialDelaySeconds: 100
          periodSeconds: 100
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /vap-saas/api/vaphealth/health-ready
            port: 9080
          initialDelaySeconds: 10
          periodSeconds: 100
      - name: li-agent
        image: $$IMAGE_REPOSITORY/symphony/li-agent:$$LI_AGENT_BUILD_NUMBER
        command:
         - /bin/sh
         - -c
         - exec /opt/li-agent/bin/run.sh
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "$$LIAGENT_CPU_LIMITS"
            memory: "$$LIAGENT_MEM_LIMITS"
        volumeMounts:
        - mountPath: /var/log
          name: li-logs
        - mountPath: /run/liagent-ini
          name: li-secret
      volumes:
      - name: li-logs
        emptyDir: {}
      - name: li-secret
        secret:
          secretName: vap-saas-sb-liagentini-$$VRBC_BUILD_NUMBER
      - name: csp-secret
        secret:
          secretName: vap-saas-sb-cspconfig-$$VRBC_BUILD_NUMBER
      - name: app-secret
        secret:
          secretName: vap-saas-sb-application-properties-$$VRBC_BUILD_NUMBER
      imagePullSecrets:
      - name: $$REPOSITORY_SECRET
      restartPolicy: Always
      terminationGracePeriodSeconds: 30